#!/usr/bin/env python3
"""Build the on-board NAND (MT29F4G08ABADA) probe-rs flash algorithm for the
apollo-f429 board and generate a target YAML.

Compiles flash_nand_fmc.c (position-independent, FMC register-level) with
arm-none-eabi-gcc, extracts the code blob + entry-point offsets, and writes
target_nand_fmc.yaml for use with:

  probe-rs download --chip-description-path target_nand_fmc.yaml \
      --chip STM32F429IG-NAND-fmc_nand --binary-format hex app.hex

The NAND replaces the W25Q64 OCTOSPI chip of h723-mini's qspi_map/algo:
address 0xC0000000 + off in the app's (SDRAM-linked) window maps to NAND
byte offset `off` (page = off/2048, col = off%2048). Sector = NAND block
(64 pages * 2048 B = 128 KiB).
"""
import base64
import subprocess
import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
GCC = r"D:/Arm/GNU Toolchain mingw-w64-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc.exe"
LD = r"D:/Arm/GNU Toolchain mingw-w64-x86_64-arm-none-eabi/bin/arm-none-eabi-ld.exe"
NM = r"D:/Arm/GNU Toolchain mingw-w64-x86_64-arm-none-eabi/bin/arm-none-eabi-nm.exe"
OBJCOPY = r"D:/Arm/GNU Toolchain mingw-w64-x86_64-arm-none-eabi/bin/arm-none-eabi-objcopy.exe"

LOAD = 0x20000000       # link base (algo.ld) - offsets are relative to this
RUNTIME_LOAD = 0x20000020  # runtime load point (probe-rs prepends a 4-byte BKPT header before it)

APP_NVM_BASE = 0xC0000000  # SDRAM bank 1 window where the app links/runs
APP_NVM_SIZE = 0x01000000  # 16 MB logical window (stored at NAND offset 0)


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"command failed: {' '.join(cmd)}\n{r.stderr}")
    return r.stdout


def main() -> int:
    src = sys.argv[1] if len(sys.argv) > 1 else "flash_nand_fmc.c"
    stem = os.path.splitext(os.path.basename(src))[0]
    base = stem[6:] if stem.startswith("flash_") else stem   # flash_nand_fmc -> nand_fmc
    page_size = sys.argv[2] if len(sys.argv) > 2 else "0x800"
    run([GCC, "-mcpu=cortex-m4", "-mthumb", "-ffreestanding", "-fno-builtin",
         "-fno-stack-protector", "-fomit-frame-pointer", "-O2", "-Wall", "-c",
         src, "-o", "flash.o"])
    run([LD, "-T", "algo.ld", "flash.o", "-o", "flash.elf"])
    run([OBJCOPY, "-O", "binary", "flash.elf", "flash.bin"])

    blob = open(os.path.join(HERE, "flash.bin"), "rb").read()
    b64 = base64.b64encode(blob).decode()

    nm = run([NM, "-n", "flash.elf"])
    sym = {}
    for line in nm.splitlines():
        parts = line.split()
        if len(parts) == 3:
            addr, _typ, name = int(parts[0], 16), parts[1], parts[2]
            sym[name] = addr - LOAD

    for fn in ("Init", "UnInit", "EraseSector", "EraseChip", "ProgramPage", "Verify"):
        if fn not in sym:
            sys.exit(f"symbol {fn} not found")

    yaml = f"""# Auto-generated by build_algo.py - NAND flash algorithm ({base}).
name: STM32F429IG NAND MT29F4G08ABADA
variants:
  - name: STM32F429IG-NAND-{base}
    package_variants:
      - STM32F429IGTx
    cores:
      - name: main
        type: armv7em
        core_access_options: !Arm
          ap: !v1 0
    memory_map:
      - !Ram
        name: SRAM
        range:
          start: 0x20000000
          end: 0x20030000
        cores:
          - main
      - !Nvm
        name: NAND
        range:
          start: {hex(APP_NVM_BASE)}
          end: {hex(APP_NVM_BASE + APP_NVM_SIZE)}
        cores:
          - main
        access:
          write: false
          boot: true
    flash_algorithms:
      - nand_mt29f4g08_stm32f429
flash_algorithms:
  - name: nand_mt29f4g08_stm32f429
    description: MT29F4G08ABADA 512MB via STM32F429IG FMC (NAND bank 3)
    default: true
    instructions: {b64}
    load_address: 0x{RUNTIME_LOAD:x}
    pc_init: 0x{sym['Init']:x}
    pc_uninit: 0x{sym['UnInit']:x}
    pc_program_page: 0x{sym['ProgramPage']:x}
    pc_erase_sector: 0x{sym['EraseSector']:x}
    pc_erase_all: 0x{sym['EraseChip']:x}
    pc_verify: 0x{sym['Verify']:x}
    data_section_offset: 0x0
    stack_size: 0x400
    flash_properties:
      address_range:
        start: {hex(APP_NVM_BASE)}
        end: {hex(APP_NVM_BASE + APP_NVM_SIZE)}
      page_size: {page_size}
      erased_byte_value: 0xff
      program_page_timeout: 500
      erase_sector_timeout: 1000
      sectors:
        - size: 0x20000
          address: 0x0
"""
    out = os.path.join(HERE, f"target_{base}.yaml")
    with open(out, "w") as f:
        f.write(yaml)
    print(f"wrote {out} (blob {len(blob)} bytes)")
    for fn in ("Init", "UnInit", "EraseSector", "EraseChip", "ProgramPage", "Verify"):
        print(f"  {fn} @ 0x{sym[fn]:x}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())